// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DarkMode: typeof import('./src/components/dark-mode.vue')['default']
    'IconPh:moon': typeof import('~icons/ph/moon')['default']
    'IconPh:sun': typeof import('~icons/ph/sun')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.7.38/node_modules/iles/dist/client/app/components/Island.vue')['default']
    NewsletterSignup: typeof import('./src/components/newsletter-signup.vue')['default']
  }
}

export { }
