[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # uncomment if using pnpm to skip npm install